"""
midan.endpoints — FastAPI app + HTTP endpoints.

Six endpoints (/analyze, /chat, /project, /interact, /health,
/rejection-patterns). /analyze, /interact, /project declare
response_model=ResponsePayload — schema is enforced at the wire boundary.
Pipeline + LLM failures surface as 500 with explicit detail; never silent.
"""
from midan.core import *  # noqa: F401,F403
from midan.pipeline import process_idea, run_inference  # noqa: F401
from midan.response import (  # noqa: F401
    build_response_payload, SchemaViolationError, _BUILDER_LOG,
    _chat_fallback, _generate_operator_reply,
    _build_projection_payload, _answer_projection_probe,
    _assess_projection_input,
    _chat_llm_reply, _sanitize_chat_output, _chat_pre_analysis_reply,
)
from midan.conversation import (  # noqa: F401
    _classify_intent, _post_decision_route, _extract_components,
    _build_analysis_text, _smart_followup, _casual_response,
    _GREET_TOKENS, _META_PHRASES, _VAGUE_STARTERS,
)


# ── extracted from api.py ─────────────────────────────────────────────


# ═══════════════════════════════════════════════════════════════
# FASTAPI APPLICATION
# ═══════════════════════════════════════════════════════════════

api = FastAPI(title="MIDAN AI Decision Engine", version="2.0")

api.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], allow_methods=["*"], allow_headers=["*"],
)


# ── Server-side session store ────────────────────────────────────────────────
# Persists startup context (profile + last L4 decision) across HTTP boundaries.
# Keyed by session_id (one UUID per conversation, generated by the frontend).
# On every chat/interact call the stored context is merged with the incoming
# context so the chat layer always has decision_state, l4_decision, and the
# startup profile — even if the client forgets to round-trip them.
_SESSION_STORE: Dict[str, Dict[str, Any]] = {}
_SESSION_MAX = 500


def _build_session_context(raw: dict) -> dict:
    feat = raw.get("idea_features") or {}
    return {
        "idea":            raw.get("idea", ""),
        "sector":          raw.get("sector", ""),
        "country":         raw.get("country", ""),
        "regime":          raw.get("regime", ""),
        "tas_score":       raw.get("tas_score", 0),
        "signal_tier":     raw.get("signal_tier", ""),
        "dominant_risk":   raw.get("dominant_risk", ""),
        "decision_state":  raw.get("decision_state", ""),
        "decision_strength": raw.get("decision_strength") or {},
        "l4_decision":     raw.get("l4_decision") or {},
        "idea_features":   feat,
        "business_model":  feat.get("business_model", ""),
        "target_segment":  feat.get("target_segment", ""),
        "stage":           feat.get("stage", ""),
        "industry":        raw.get("sector", ""),
        "region":          raw.get("country", ""),
        "strategic_interpretation": raw.get("strategic_interpretation", ""),
        "key_driver":      raw.get("key_driver", ""),
        "main_risk":       raw.get("main_risk", ""),
        "l3_reasoning":    raw.get("l3_reasoning") or {},
    }


def _store_session(session_id: Optional[str], raw: dict) -> None:
    if not session_id:
        return
    if len(_SESSION_STORE) >= _SESSION_MAX:
        del _SESSION_STORE[next(iter(_SESSION_STORE))]
    _SESSION_STORE[session_id] = _build_session_context(raw)


def _resolve_context(session_id: Optional[str], incoming: dict) -> dict:
    """Merge stored session context with incoming context. Incoming wins on conflict."""
    if not session_id:
        return incoming
    stored = _SESSION_STORE.get(session_id)
    if not stored:
        return incoming
    return {**stored, **incoming}


@api.post("/analyze", response_model=ResponsePayload)
async def analyze_idea(req: IdeaRequest) -> ResponsePayload:
    """
    Run the full pipeline and return a strict ResponsePayload.

    Schema is enforced by `response_model=ResponsePayload`. Any field-shape
    drift inside `build_response_payload` raises ValidationError, which
    surfaces as a 500 with explicit detail — never silent auto-correction.
    """
    request_id = new_request_id()
    if not MODELS_LOADED:
        log_failure(request_id, endpoint="/analyze", kind="models_not_loaded",
                    detail="MODELS_LOADED is False at endpoint entry")
        raise HTTPException(status_code=500, detail="Models failed to load.")
    sector_key   = SECTOR_LABEL_MAP.get(req.sector, "fintech")
    country_code = req.country.split(" — ")[0]
    if not req.idea or len(req.idea.strip()) < 5:
        log_failure(request_id, endpoint="/analyze", kind="idea_too_short",
                    detail=f"len={len(req.idea or '')}")
        raise HTTPException(status_code=400, detail="Idea too short")
    try:
        raw = process_idea(req.idea, sector_key, country_code)
    except Exception as pipeline_err:
        log_failure(request_id, endpoint="/analyze", kind="pipeline_error",
                    detail=f"{type(pipeline_err).__name__}: {pipeline_err!r}")
        raise HTTPException(status_code=500, detail=f"pipeline_error: {pipeline_err!r}")

    # Map raw outcome → strict payload. Outcome is determined explicitly,
    # NOT by auto-detection inside build_response_payload.
    if raw.get("invalid_idea"):
        outcome = 'rejected'
    elif raw.get("clarification_required"):
        outcome = 'clarification_required'
    else:
        outcome = 'decided'
    try:
        payload = build_response_payload(raw, outcome=outcome)
    except (SchemaViolationError, ValidationError) as schema_err:
        log_failure(request_id, endpoint="/analyze", kind="response_schema_violation",
                    detail=f"{schema_err!r} — raw outcome={outcome}")
        raise HTTPException(status_code=500, detail=f"response_schema_violation: {schema_err!r}")

    _store_session(req.session_id, raw)
    log_decision(request_id, raw, endpoint="/analyze")
    return payload


# ── CHAT FALLBACK (no LLM) — L4-grounded ─────────────────────────────────────
# Every reply is built from the L4 decision envelope, NOT from legacy TAS/tier
# fields. Branches by post-decision conversation mode (RESOLVING_CONFLICT,
# ADVISORY_ONLY, RE_CLARIFY, STANDARD_ADVISOR). When prior decision is missing
# or invalid, the chat refuses to advise and re-prompts for the idea.

@api.post("/chat")
async def chat_interaction(req: ChatRequest):
    """
    Single chat entry point. All chat replies (including those routed in from
    /interact) flow through here.

    Behavior contract:
      1. If GROQ_API_KEY is configured → LLM is used (unified system prompt
         built by _chat_llm_reply, mode-aware, with strict L4 input contract).
      2. Hard L4 guard inside _chat_llm_reply: if no decision_state in context,
         it returns a consultative pre-analysis reply WITHOUT calling the LLM
         (never sends empty L4 fields to the model).
      3. On any LLM API failure → sanitized _chat_fallback (never raw output).
      4. Every returned reply is run through _sanitize_chat_output as a final
         defence-in-depth strip of internal labels, layer names, debug stamps,
         and UNKNOWN leakage.
    """
    # Merge session context so the chat layer always has decision_state + startup profile
    resolved_ctx = _resolve_context(getattr(req, 'session_id', None), req.context)
    if resolved_ctx is not req.context:
        req = ChatRequest(context=resolved_ctx, messages=req.messages,
                          session_id=getattr(req, 'session_id', None))
    try:
        reply = _chat_llm_reply(req)
        if reply:
            return {"success": True, "reply": _sanitize_chat_output(reply)}
        # LLM unavailable (no key / no client) — sanitized heuristic.
        return {"success": True, "reply": _sanitize_chat_output(_chat_fallback(req))}
    except Exception as llm_err:
        __import__('logging').getLogger("midan.chat").warning(
            "[CHAT] LLM call failed (%s: %r) — falling back to L4-grounded heuristic",
            type(llm_err).__name__, llm_err,
        )
        return {"success": True, "reply": _sanitize_chat_output(_chat_fallback(req))}


class InteractRequest(BaseModel):
    context: Dict[str, Any]
    messages: List[ChatMessage]
    session_id: Optional[str] = None


@api.post("/project", response_model=ResponsePayload)
async def projection_route(req: ProjectionRequest) -> ResponsePayload:
    """
    Projection endpoint with strict ResponsePayload contract.

    Five outcome branches, each producing a fully-validated payload:
      1. Probe question  → PRE_ANALYSIS with the answer in `reply`
      2. Low-quality idea → PRE_ANALYSIS with quality assessment in `quality`
      3. L0 rejection    → REJECTED with projection extras
      4. L1 fail-fast    → CLARIFICATION_REQUIRED with projection extras
      5. Full analysis   → decided state (GO/CONDITIONAL/...) with projection
    """
    idea_text = (req.idea or "").strip()
    context = req.context or {}
    question = (req.question or "").strip()
    request_id = new_request_id()

    # ── Branch 1: probe question over existing analysis ──────────────────
    if question:
        try:
            answer = _answer_projection_probe(question, context)
            payload = build_response_payload(
                outcome='pre_analysis',
                reply=answer,
                type_='probe',
            )
            log_decision(request_id, {}, endpoint="/project:probe")
            return payload
        except (SchemaViolationError, ValidationError) as schema_err:
            log_failure(request_id, endpoint="/project:probe", kind="response_schema_violation",
                        detail=f"{schema_err!r}")
            raise HTTPException(status_code=500, detail=f"response_schema_violation: {schema_err!r}")

    # ── Branch 2: input quality below threshold (no pipeline run) ────────
    quality = _assess_projection_input(idea_text)
    if not quality["analysis_allowed"]:
        legacy_projection = {
            "quality": quality,
            "headline": "Interpretation forming",
            "direct_thesis": quality["refusal"],
            "direct_weakness": "",
            "decision_label": "Signal below threshold",
            "decision_body": "MIDAN will not issue a market verdict until the product, user, and problem are explicit.",
            "focus_line": "Define the mechanism, the user, and the pain in one compact statement.",
            "counter_thesis": "",
            "guidance": quality["guidance"],
        }
        try:
            payload = build_response_payload(
                outcome='pre_analysis',
                type_='interpretation',
            )
            payload.projection = legacy_projection
            payload.quality    = quality
            log_decision(request_id, {}, endpoint="/project:low_quality")
            return payload
        except (SchemaViolationError, ValidationError) as schema_err:
            log_failure(request_id, endpoint="/project:low_quality",
                        kind="response_schema_violation", detail=f"{schema_err!r}")
            raise HTTPException(status_code=500, detail=f"response_schema_violation: {schema_err!r}")

    # ── Branches 3-5: run the pipeline ───────────────────────────────────
    try:
        raw = process_idea(idea_text)
    except Exception as pipeline_err:
        log_failure(request_id, endpoint="/project", kind="pipeline_error",
                    detail=f"{type(pipeline_err).__name__}: {pipeline_err!r}")
        raise HTTPException(status_code=500, detail=f"pipeline_error: {pipeline_err!r}")

    if raw.get("invalid_idea"):
        outcome = 'rejected'
        legacy_projection = {
            "quality": quality,
            "headline": "Concept rejected",
            "direct_thesis": raw.get("one_line_verdict", "Not a viable business concept."),
            "direct_weakness": raw.get("what_is_missing", ""),
            "decision_label": raw.get("decision_badge", "Invalid"),
            "decision_body": raw.get("message", ""),
            "focus_line": "Correct the structural failure before asking for a market read.",
            "counter_thesis": "",
            "guidance": raw.get("how_to_fix", []),
        }
    elif raw.get("clarification_required"):
        outcome = 'clarification_required'
        clar = raw.get("clarification", {}) or {}
        legacy_projection = {
            "quality": quality,
            "headline": "Clarification required",
            "direct_thesis": raw.get("one_line_verdict", "L1 confidence below threshold."),
            "direct_weakness": raw.get("message", ""),
            "decision_label": raw.get("decision_badge", "CLARIFICATION REQUIRED"),
            "decision_body": (
                "MIDAN halts before L2/L3/L4 when key idea fields are unknown "
                "or internally inconsistent. Resolve the clarifications below "
                "and resubmit."
            ),
            "focus_line": "Provide the missing components — do not force analysis on partial input.",
            "counter_thesis": "",
            "guidance": clar.get("questions", []) or raw.get("how_to_fix", []),
        }
    else:
        outcome = 'decided'
        legacy_projection = _build_projection_payload(idea_text, raw, quality)

    # Map outcome to back-compat `type` label that legacy clients of /project
    # were already reading. The schema-canonical field is `decision_state`.
    type_label = {
        'rejected':                'invalid',
        'clarification_required':  'clarification_required',
        'decided':                 'analysis',
    }[outcome]
    try:
        payload = build_response_payload(
            raw, outcome=outcome, type_=type_label,
        )
        payload.projection = legacy_projection
        payload.quality    = quality
        log_decision(request_id, raw, endpoint=f"/project:{outcome}")
        return payload
    except (SchemaViolationError, ValidationError) as schema_err:
        log_failure(request_id, endpoint=f"/project:{outcome}",
                    kind="response_schema_violation", detail=f"{schema_err!r}")
        raise HTTPException(status_code=500, detail=f"response_schema_violation: {schema_err!r}")


def _interact_payload_or_500(builder_call):
    """Wrap build_response_payload in the shared schema-violation handler."""
    try:
        return builder_call()
    except (SchemaViolationError, ValidationError) as schema_err:
        _BUILDER_LOG.error("[interact] response schema violation: %r", schema_err)
        raise HTTPException(status_code=500, detail=f"response_schema_violation: {schema_err!r}")


@api.post("/interact", response_model=ResponsePayload)
async def interact_route(req: InteractRequest) -> ResponsePayload:
    """
    Conversation Intelligence Layer — classifies intent before any pipeline decision,
    then constructs a strict ResponsePayload.

    Intent flow (priority order):
      OVERRIDE_COMMAND → run analysis immediately, skip all questions
      CLARIFICATION    → route to strategic advisor chat (post-analysis)
      CASUAL           → natural response — no pipeline
      META             → explain MIDAN briefly — no pipeline
      GREETING         → "what are you building?" — no pipeline
      ANALYSIS_REQUEST → run pipeline immediately (or after anti-loop trigger)
      PARTIAL_IDEA     → ask ONE smart follow-up — no pipeline

    Every branch returns a ResponsePayload satisfying the strict schema.
    """
    request_id = new_request_id()
    # Resolve session context before any processing — ensures decision_state and
    # startup profile are always present even if the client omitted them.
    resolved_ctx = _resolve_context(req.session_id, req.context)

    last_user_msg = next(
        (m.content for m in reversed(req.messages) if m.role == "user"), ""
    )
    t  = last_user_msg.lower().strip()
    wc = len(t.split())

    intent_data = _classify_intent(last_user_msg, resolved_ctx, req.messages)
    intent = intent_data['intent']

    # ── CLARIFICATION: post-analysis turn — route by L4 decision mode ────────
    if intent == 'CLARIFICATION':
        route   = _post_decision_route(resolved_ctx)
        chat_req = ChatRequest(context=resolved_ctx, messages=req.messages,
                               session_id=req.session_id)
        chat_res = await chat_interaction(chat_req)
        type_map = {
            'RESOLVING_CONFLICT': 'conflict_resolution',
            'ADVISORY_ONLY':      'advisory',
            'RE_CLARIFY':         'reclarify',
            'STANDARD_ADVISOR':   'chat',
        }
        # The L4 envelope sits inside the request context (round-tripped from
        # a prior /analyze call). If it's present, build a `decided` payload
        # so the schema reflects the actual decision state. If not, fall back
        # to PRE_ANALYSIS — never silently invent a decision.
        prior_l4 = resolved_ctx.get("l4_decision")
        if prior_l4 and resolved_ctx.get("decision_state"):
            # Re-wrap as a decided payload using the prior L4 envelope.
            synthetic_raw = dict(resolved_ctx)
            return _interact_payload_or_500(lambda: build_response_payload(
                synthetic_raw, outcome='decided',
                reply=chat_res.get("reply", ""),
                type_=type_map.get(route['mode'], 'chat'),
            ))
        return _interact_payload_or_500(lambda: build_response_payload(
            outcome='pre_analysis',
            reply=chat_res.get("reply", ""),
            type_=type_map.get(route['mode'], 'chat'),
        ))

    # ── CASUAL / GREETING / META / vague / PARTIAL_IDEA ─────────────────────
    # All non-pipeline pre-analysis turns route through chat_interaction so
    # the LLM generates the reply (with a pre-analysis system prompt). Intent
    # classification is still used to decide WHETHER to run the pipeline; only
    # the reply text generation is delegated to Groq. Heuristic `_casual_response`
    # / `_smart_followup` survive only as fallbacks inside _chat_fallback when
    # the LLM is unavailable or fails.

    is_greeting = wc <= 6 and any(t == g or t.startswith(g) for g in _GREET_TOKENS)
    is_meta     = any(phrase in t for phrase in _META_PHRASES)
    is_purely_vague = (
        wc <= 15
        and any(t.startswith(v) or t == v.strip() for v in _VAGUE_STARTERS)
        and not _extract_components(last_user_msg)["has_problem"]
        and not _extract_components(last_user_msg)["has_solution"]
    )

    if intent in ('CASUAL', 'PARTIAL_IDEA') or is_greeting or is_meta or is_purely_vague:
        chat_req = ChatRequest(context=resolved_ctx, messages=req.messages,
                               session_id=req.session_id)
        chat_res = await chat_interaction(chat_req)
        reply = chat_res.get("reply", "")

        # PARTIAL_IDEA with actual idea content → 'clarifying' so the frontend
        # tracks the clarification state. Pure vague starter / casual / greeting
        # / meta → 'chat' (no real idea content yet, no clarification state).
        if intent == 'PARTIAL_IDEA' and not is_purely_vague:
            prior_state  = resolved_ctx.get("clarification_state", {}) or {}
            merged_state = _extract_components(last_user_msg, prior_state)
            return _interact_payload_or_500(lambda: build_response_payload(
                outcome='pre_analysis',
                reply=reply,
                type_='clarifying',
                clarification_state=merged_state,
            ))
        return _interact_payload_or_500(lambda: build_response_payload(
            outcome='pre_analysis', reply=reply, type_='chat',
        ))

    # ── ANALYSIS_REQUEST or OVERRIDE_COMMAND: run pipeline ──────────────────
    analysis_text = _build_analysis_text(last_user_msg, resolved_ctx, req.messages)
    try:
        raw = process_idea(analysis_text)
    except Exception as pipeline_err:
        log_failure(request_id, endpoint="/interact", kind="pipeline_error",
                    detail=f"{type(pipeline_err).__name__}: {pipeline_err!r}")
        raise HTTPException(status_code=500, detail=f"pipeline_error: {pipeline_err!r}")

    if raw.get("invalid_idea"):
        verdict  = raw.get("one_line_verdict", "Not a viable business concept.")
        missing  = raw.get("what_is_missing", "")
        reply    = verdict
        if missing:
            reply += f"\n\n**What's missing:** {missing}"
        payload = _interact_payload_or_500(lambda: build_response_payload(
            raw, outcome='rejected', reply=reply, type_='invalid',
        ))
        log_decision(request_id, raw, endpoint="/interact:rejected")
        return payload

    if raw.get("clarification_required"):
        clar      = raw.get("clarification", {}) or {}
        questions = clar.get("questions", []) or []
        verdict   = raw.get("one_line_verdict", "Clarification required before analysis.")
        reply     = verdict
        if questions:
            reply += "\n\n" + "\n".join(f"- {q}" for q in questions)
        merged_state = _extract_components(analysis_text, resolved_ctx.get("clarification_state"))
        payload = _interact_payload_or_500(lambda: build_response_payload(
            raw, outcome='clarification_required', reply=reply, type_='clarifying',
            clarification_state=merged_state,
        ))
        log_decision(request_id, raw, endpoint="/interact:clarification_required")
        return payload

    # Decided outcome → run operator reply, wrap in payload, persist session
    reply = _generate_operator_reply(raw, analysis_text)
    payload = _interact_payload_or_500(lambda: build_response_payload(
        raw, outcome='decided', reply=reply, type_='analysis',
    ))
    _store_session(req.session_id, raw)
    log_decision(request_id, raw, endpoint="/interact:decided")
    return payload


@api.get("/health")
async def health():
    return {
        "status":        "ok",
        "models_loaded": MODELS_LOADED,
        "version":       "3.0 — conversation intelligence + 3-tier L0 + how_to_fix engine",
    }


@api.get("/rejection-patterns")
async def rejection_patterns():
    """Returns session-level rejection pattern statistics for analysis."""
    if not _REJECTION_LOG:
        return {"total": 0, "patterns": [], "by_severity": {}, "by_type": {}}
    from collections import Counter
    by_type     = Counter(r['type']     for r in _REJECTION_LOG)
    by_severity = Counter(r['severity'] for r in _REJECTION_LOG)
    recent = _REJECTION_LOG[-10:][::-1]
    return {
        "total":       len(_REJECTION_LOG),
        "by_severity": dict(by_severity),
        "by_type":     dict(by_type),
        "recent":      [{"type": r['type'], "severity": r['severity'], "snippet": r['snippet']} for r in recent],
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("api:api", host="0.0.0.0", port=8000, reload=True)



# Export everything defined in this module — including underscore-prefixed
# helpers — so other midan submodules can wildcard-import the full surface.
__all__ = [name for name in list(globals().keys()) if not name.startswith('__')]
