"""
midan.endpoints — FastAPI app + HTTP endpoints.

Six endpoints (/analyze, /chat, /project, /interact, /health,
/rejection-patterns). /analyze, /interact, /project declare
response_model=ResponsePayload — schema is enforced at the wire boundary.
Pipeline + LLM failures surface as 500 with explicit detail; never silent.
"""
import pathlib, json, os
from fastapi.responses import FileResponse
from midan.core import *  # noqa: F401,F403
from midan.pipeline import process_idea, run_inference  # noqa: F401
from midan.outcome_feedback import log_outcome, compute_calibration_metrics, load_outcomes
from midan.drift_monitor import check_drift, load_prediction_log
from midan.response import (  # noqa: F401
    build_response_payload, SchemaViolationError, _BUILDER_LOG,
    _chat_fallback, _generate_operator_reply,
    _build_projection_payload, _answer_projection_probe,
    _assess_projection_input,
    _chat_llm_reply, _sanitize_chat_output, _chat_pre_analysis_reply,
    _PRE_ANALYSIS_ERROR_FALLBACK,
)
from midan.conversation import (  # noqa: F401
    _classify_intent, _post_decision_route, _extract_components,
    _build_analysis_text, _smart_followup, _casual_response,
    _GREET_TOKENS, _META_PHRASES, _VAGUE_STARTERS,
)


# ── extracted from api.py ─────────────────────────────────────────────

import logging as _logging, pathlib as _pathlib
_TRACE_LOG = _logging.getLogger("midan.trace")
if not _TRACE_LOG.handlers:
    _trace_path = _pathlib.Path(__file__).parent.parent / "trace.log"
    _trace_fh = _logging.FileHandler(str(_trace_path), mode="a", encoding="utf-8")
    _trace_fh.setLevel(_logging.DEBUG)
    _trace_fh.setFormatter(_logging.Formatter("%(asctime)s %(levelname)s %(message)s"))
    _TRACE_LOG.addHandler(_trace_fh)
    _TRACE_LOG.setLevel(_logging.DEBUG)
    _TRACE_LOG.propagate = False

# ═══════════════════════════════════════════════════════════════
# FASTAPI APPLICATION
# ═══════════════════════════════════════════════════════════════

api = FastAPI(title="MIDAN AI Decision Engine", version="2.0")

api.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], allow_methods=["*"], allow_headers=["*"],
)


# ── Server-side session store ────────────────────────────────────────────────
# we persist startup context here (profile + last L4 decision) across HTTP boundaries;
# we key by session_id — one UUID per conversation, generated by the frontend;
# on every chat/interact call we merge the stored context with the incoming context
# so the chat layer always has decision_state, l4_decision, and the startup profile —
# even if the client forgets to round-trip them
_SESSION_STORE: Dict[str, Dict[str, Any]] = {}
_SESSION_MAX = 500


def _build_session_context(raw: dict) -> dict:
    feat = raw.get("idea_features") or {}
    return {
        "idea":            raw.get("idea", ""),
        "sector":          raw.get("sector", ""),
        "country":         raw.get("country", ""),
        "regime":          raw.get("regime", ""),
        "tas_score":       raw.get("tas_score", 0),
        "signal_tier":     raw.get("signal_tier", ""),
        "dominant_risk":   raw.get("dominant_risk", ""),
        "decision_state":  raw.get("decision_state", ""),
        "decision_strength": raw.get("decision_strength") or {},
        "l4_decision":     raw.get("l4_decision") or {},
        "idea_features":   feat,
        "business_model":  feat.get("business_model", ""),
        "target_segment":  feat.get("target_segment", ""),
        "stage":           feat.get("stage", ""),
        "industry":        raw.get("sector", ""),
        "region":          raw.get("country", ""),
        "strategic_interpretation": raw.get("strategic_interpretation", ""),
        "key_driver":      raw.get("key_driver", ""),
        "main_risk":       raw.get("main_risk", ""),
        "l3_reasoning":    raw.get("l3_reasoning") or {},
    }


def _store_session(session_id: Optional[str], raw: dict) -> None:
    if not session_id:
        return
    if len(_SESSION_STORE) >= _SESSION_MAX:
        del _SESSION_STORE[next(iter(_SESSION_STORE))]
    _SESSION_STORE[session_id] = _build_session_context(raw)


def _resolve_context(session_id: Optional[str], incoming: dict) -> dict:
    """Merge stored session context with incoming context. Incoming wins on conflict."""
    if not session_id:
        return incoming
    stored = _SESSION_STORE.get(session_id)
    if not stored:
        return incoming
    return {**stored, **incoming}


@api.post("/analyze", response_model=ResponsePayload)
async def analyze_idea(req: IdeaRequest) -> ResponsePayload:
    """
    Run the full pipeline and return a strict ResponsePayload.

    Schema is enforced by `response_model=ResponsePayload`. Any field-shape
    drift inside `build_response_payload` raises ValidationError, which
    surfaces as a 500 with explicit detail — never silent auto-correction.
    """
    request_id = new_request_id()
    if not MODELS_LOADED:
        log_failure(request_id, endpoint="/analyze", kind="models_not_loaded",
                    detail="MODELS_LOADED is False at endpoint entry")
        raise HTTPException(status_code=500, detail="Models failed to load.")
    sector_key   = SECTOR_LABEL_MAP.get(req.sector, "fintech")
    country_code = req.country.split(" — ")[0]
    if not req.idea or len(req.idea.strip()) < 5:
        log_failure(request_id, endpoint="/analyze", kind="idea_too_short",
                    detail=f"len={len(req.idea or '')}")
        raise HTTPException(status_code=400, detail="Idea too short")
    try:
        raw = process_idea(req.idea, sector_key, country_code)
    except Exception as pipeline_err:
        log_failure(request_id, endpoint="/analyze", kind="pipeline_error",
                    detail=f"{type(pipeline_err).__name__}: {pipeline_err!r}")
        raise HTTPException(status_code=500, detail=f"pipeline_error: {pipeline_err!r}")

    # we map raw outcome to a strict payload here; we determine outcome explicitly —
    # NOT by auto-detection inside build_response_payload
    if raw.get("invalid_idea"):
        outcome = 'rejected'
    elif raw.get("clarification_required"):
        outcome = 'clarification_required'
    else:
        outcome = 'decided'
    try:
        payload = build_response_payload(raw, outcome=outcome)
    except (SchemaViolationError, ValidationError) as schema_err:
        log_failure(request_id, endpoint="/analyze", kind="response_schema_violation",
                    detail=f"{schema_err!r} — raw outcome={outcome}")
        raise HTTPException(status_code=500, detail=f"response_schema_violation: {schema_err!r}")

    _store_session(req.session_id, raw)
    log_decision(request_id, raw, endpoint="/analyze")
    return payload


# ── CHAT FALLBACK (no LLM) — L4-grounded ─────────────────────────────────────
# we build every reply from the L4 decision envelope, NOT from legacy TAS/tier fields;
# we branch by post-decision conversation mode (RESOLVING_CONFLICT, ADVISORY_ONLY,
# RE_CLARIFY, STANDARD_ADVISOR); when the prior decision is missing or invalid,
# we refuse to advise and re-prompt for the idea

@api.post("/chat")
async def chat_interaction(req: ChatRequest):
    """
    Single chat entry point. All chat replies (including those routed in from
    /interact) flow through here.

    Behavior contract:
      1. Gemini is used for LLM replies (unified system prompt built by
         _chat_llm_reply, mode-aware, with strict L4 input contract).
      2. Hard L4 guard inside _chat_llm_reply: if no decision_state in context,
         it returns a consultative pre-analysis reply WITHOUT calling the LLM
         (never sends empty L4 fields to the model).
      3. On any LLM API failure → sanitized _chat_fallback (never raw output).
      4. Every returned reply is run through _sanitize_chat_output as a final
         defence-in-depth strip of internal labels, layer names, debug stamps,
         and UNKNOWN leakage.
    """
    # we merge session context here so the chat layer always has decision_state + startup profile
    resolved_ctx = _resolve_context(getattr(req, 'session_id', None), req.context)
    if resolved_ctx is not req.context:
        req = ChatRequest(context=resolved_ctx, messages=req.messages,
                          session_id=getattr(req, 'session_id', None))
    decision_state = resolved_ctx.get('decision_state') or (resolved_ctx.get('l4_decision') or {}).get('decision_state')

    # ── Pre-analysis: Gemini owns every reply via _chat_pre_analysis_reply.
    # That function always returns a string — the error fallback is baked in.
    # No heuristic intercept exists here.
    if not decision_state:
        _TRACE_LOG.info("[TRACE][chat_interaction] PRE-ANALYSIS → _chat_pre_analysis_reply")
        reply = _chat_pre_analysis_reply(req)
        is_fallback = (reply == _PRE_ANALYSIS_ERROR_FALLBACK)
        _TRACE_LOG.info("[TRACE][chat_interaction] reply=%r | is_fallback=%s", reply[:120], is_fallback)
        return {"success": True, "reply": _sanitize_chat_output(reply), "is_fallback": is_fallback}

    # ── Post-analysis: LLM with full decision context, _chat_fallback on failure
    try:
        _TRACE_LOG.info("[TRACE][chat_interaction] POST-ANALYSIS → _chat_llm_reply")
        reply = _chat_llm_reply(req)
        if reply:
            _TRACE_LOG.info("[TRACE][chat_interaction] LLM CALLED (post) — reply=%r", reply[:120])
            return {"success": True, "reply": _sanitize_chat_output(reply), "is_fallback": False}
        __import__('logging').getLogger("midan.chat").warning("[CHAT] post-analysis LLM returned None → _chat_fallback")
        _TRACE_LOG.warning("[TRACE][chat_interaction] LLM SKIPPED (post, None) → _chat_fallback")
        fb = _chat_fallback(req)
        _TRACE_LOG.warning("[TRACE][chat_interaction] POST FALLBACK: %r", fb[:120])
        return {"success": True, "reply": _sanitize_chat_output(fb), "is_fallback": True}
    except Exception as llm_err:
        __import__('logging').getLogger("midan.chat").warning(
            "[CHAT] post-analysis LLM failed (%s: %r) → _chat_fallback", type(llm_err).__name__, llm_err)
        _TRACE_LOG.warning("[TRACE][chat_interaction] LLM SKIPPED (post, exception) → _chat_fallback")
        fb = _chat_fallback(req)
        _TRACE_LOG.warning("[TRACE][chat_interaction] POST FALLBACK: %r", fb[:120])
        return {"success": True, "reply": _sanitize_chat_output(fb), "is_fallback": True}


class InteractRequest(BaseModel):
    context: Dict[str, Any]
    messages: List[ChatMessage]
    session_id: Optional[str] = None


class OutcomeSubmission(BaseModel):
    decision_id:             str
    sector:                  str
    country:                 str
    regime:                  str
    predicted_state:         str
    outcome_value:           str
    react_path:              str = ""
    intelligent_score:       float = 0.0
    is_components:           Optional[Dict[str, float]] = None
    time_to_outcome_days:    Optional[int] = None
    outcome_notes:           str = ""
    supersedes_decision_id:  Optional[str] = None


@api.post("/project", response_model=ResponsePayload)
async def projection_route(req: ProjectionRequest) -> ResponsePayload:
    """
    Projection endpoint with strict ResponsePayload contract.

    Five outcome branches, each producing a fully-validated payload:
      1. Probe question  → PRE_ANALYSIS with the answer in `reply`
      2. Low-quality idea → PRE_ANALYSIS with quality assessment in `quality`
      3. L0 rejection    → REJECTED with projection extras
      4. L1 fail-fast    → CLARIFICATION_REQUIRED with projection extras
      5. Full analysis   → decided state (GO/CONDITIONAL/...) with projection
    """
    idea_text = (req.idea or "").strip()
    context = req.context or {}
    question = (req.question or "").strip()
    request_id = new_request_id()

    # ── Branch 1: we handle probe questions over existing analysis first ──────────────────
    if question:
        try:
            answer = _answer_projection_probe(question, context)
            payload = build_response_payload(
                outcome='pre_analysis',
                reply=answer,
                type_='probe',
            )
            log_decision(request_id, {}, endpoint="/project:probe")
            return payload
        except (SchemaViolationError, ValidationError) as schema_err:
            log_failure(request_id, endpoint="/project:probe", kind="response_schema_violation",
                        detail=f"{schema_err!r}")
            raise HTTPException(status_code=500, detail=f"response_schema_violation: {schema_err!r}")

    # ── Branch 2: we skip the pipeline when input quality is below threshold ────────
    quality = _assess_projection_input(idea_text)
    if not quality["analysis_allowed"]:
        legacy_projection = {
            "quality": quality,
            "headline": "Interpretation forming",
            "direct_thesis": quality["refusal"],
            "direct_weakness": "",
            "decision_label": "Signal below threshold",
            "decision_body": "MIDAN will not issue a market verdict until the product, user, and problem are explicit.",
            "focus_line": "Define the mechanism, the user, and the pain in one compact statement.",
            "counter_thesis": "",
            "guidance": quality["guidance"],
        }
        try:
            payload = build_response_payload(
                outcome='pre_analysis',
                type_='interpretation',
            )
            payload.projection = legacy_projection
            payload.quality    = quality
            log_decision(request_id, {}, endpoint="/project:low_quality")
            return payload
        except (SchemaViolationError, ValidationError) as schema_err:
            log_failure(request_id, endpoint="/project:low_quality",
                        kind="response_schema_violation", detail=f"{schema_err!r}")
            raise HTTPException(status_code=500, detail=f"response_schema_violation: {schema_err!r}")

    # ── Branches 3-5: we run the pipeline for all remaining cases ───────────────────────────────────
    try:
        raw = process_idea(idea_text)
    except Exception as pipeline_err:
        log_failure(request_id, endpoint="/project", kind="pipeline_error",
                    detail=f"{type(pipeline_err).__name__}: {pipeline_err!r}")
        raise HTTPException(status_code=500, detail=f"pipeline_error: {pipeline_err!r}")

    if raw.get("invalid_idea"):
        outcome = 'rejected'
        legacy_projection = {
            "quality": quality,
            "headline": "Concept rejected",
            "direct_thesis": raw.get("one_line_verdict", "Not a viable business concept."),
            "direct_weakness": raw.get("what_is_missing", ""),
            "decision_label": raw.get("decision_badge", "Invalid"),
            "decision_body": raw.get("message", ""),
            "focus_line": "Correct the structural failure before asking for a market read.",
            "counter_thesis": "",
            "guidance": raw.get("how_to_fix", []),
        }
    elif raw.get("clarification_required"):
        outcome = 'clarification_required'
        clar = raw.get("clarification", {}) or {}
        legacy_projection = {
            "quality": quality,
            "headline": "Clarification required",
            "direct_thesis": raw.get("one_line_verdict", "L1 confidence below threshold."),
            "direct_weakness": raw.get("message", ""),
            "decision_label": raw.get("decision_badge", "CLARIFICATION REQUIRED"),
            "decision_body": (
                "MIDAN halts before L2/L3/L4 when key idea fields are unknown "
                "or internally inconsistent. Resolve the clarifications below "
                "and resubmit."
            ),
            "focus_line": "Provide the missing components — do not force analysis on partial input.",
            "counter_thesis": "",
            "guidance": clar.get("questions", []) or raw.get("how_to_fix", []),
        }
    else:
        outcome = 'decided'
        legacy_projection = _build_projection_payload(idea_text, raw, quality)

    # we map outcome to a back-compat `type` label that legacy clients of /project
    # were already reading — the schema-canonical field is `decision_state`
    type_label = {
        'rejected':                'invalid',
        'clarification_required':  'clarification_required',
        'decided':                 'analysis',
    }[outcome]
    try:
        payload = build_response_payload(
            raw, outcome=outcome, type_=type_label,
        )
        payload.projection = legacy_projection
        payload.quality    = quality
        log_decision(request_id, raw, endpoint=f"/project:{outcome}")
        return payload
    except (SchemaViolationError, ValidationError) as schema_err:
        log_failure(request_id, endpoint=f"/project:{outcome}",
                    kind="response_schema_violation", detail=f"{schema_err!r}")
        raise HTTPException(status_code=500, detail=f"response_schema_violation: {schema_err!r}")


def _interact_payload_or_500(builder_call):
    """Wrap build_response_payload in the shared schema-violation handler."""
    try:
        return builder_call()
    except (SchemaViolationError, ValidationError) as schema_err:
        _BUILDER_LOG.error("[interact] response schema violation: %r", schema_err)
        raise HTTPException(status_code=500, detail=f"response_schema_violation: {schema_err!r}")


@api.post("/interact", response_model=ResponsePayload)
async def interact_route(req: InteractRequest) -> ResponsePayload:
    """
    Conversation Intelligence Layer — classifies intent before any pipeline decision,
    then constructs a strict ResponsePayload.

    Intent flow (priority order):
      OVERRIDE_COMMAND → run analysis immediately, skip all questions
      CLARIFICATION    → route to strategic advisor chat (post-analysis)
      CASUAL           → natural response — no pipeline
      META             → explain MIDAN briefly — no pipeline
      GREETING         → "what are you building?" — no pipeline
      ANALYSIS_REQUEST → run pipeline immediately (or after anti-loop trigger)
      PARTIAL_IDEA     → ask ONE smart follow-up — no pipeline

    Every branch returns a ResponsePayload satisfying the strict schema.
    """
    request_id = new_request_id()
    # we resolve session context before any processing — this ensures decision_state and
    # the startup profile are always present even if the client omitted them
    resolved_ctx = _resolve_context(req.session_id, req.context)

    last_user_msg = next(
        (m.content for m in reversed(req.messages) if m.role == "user"), ""
    )
    t  = last_user_msg.lower().strip()
    wc = len(t.split())

    _TRACE_LOG.info("[TRACE][interact] ── NEW TURN ──────────────────────────────────")
    _TRACE_LOG.info("[TRACE][interact] RAW INPUT: %r | wc=%d", last_user_msg, wc)

    intent_data = _classify_intent(last_user_msg, resolved_ctx, req.messages)
    intent = intent_data['intent']
    _TRACE_LOG.info("[TRACE][interact] INTENT: %s | reason=%s | should_analyze=%s",
                    intent, intent_data.get('reason'), intent_data.get('should_analyze'))

    # ── CLARIFICATION: post-analysis turn — we route by L4 decision mode ────────
    if intent == 'CLARIFICATION':
        _TRACE_LOG.info("[TRACE][interact] BRANCH: CLARIFICATION (post-analysis)")
        route   = _post_decision_route(resolved_ctx)
        chat_req = ChatRequest(context=resolved_ctx, messages=req.messages,
                               session_id=req.session_id)
        chat_res = await chat_interaction(chat_req)
        type_map = {
            'RESOLVING_CONFLICT': 'conflict_resolution',
            'ADVISORY_ONLY':      'advisory',
            'RE_CLARIFY':         'reclarify',
            'STANDARD_ADVISOR':   'chat',
        }
        # we read the L4 envelope from the request context (round-tripped from a prior /analyze call);
        # if it's present, we build a `decided` payload so the schema reflects the actual decision state;
        # if not, we fall back to PRE_ANALYSIS — we never silently invent a decision
        prior_l4 = resolved_ctx.get("l4_decision")
        _chat_reply = chat_res.get("reply", "")
        _chat_is_fb = chat_res.get("is_fallback", False)
        _chat_type  = type_map.get(route['mode'], 'chat')
        if prior_l4 and resolved_ctx.get("decision_state"):
            # we re-wrap as a decided payload using the prior L4 envelope
            synthetic_raw = dict(resolved_ctx)
            return _interact_payload_or_500(lambda: build_response_payload(
                synthetic_raw, outcome='decided',
                reply=_chat_reply, type_=_chat_type,
                is_fallback=_chat_is_fb,
            ))
        return _interact_payload_or_500(lambda: build_response_payload(
            outcome='pre_analysis',
            reply=_chat_reply, type_=_chat_type,
            is_fallback=_chat_is_fb,
        ))

    # ── CASUAL / GREETING / META / vague / PARTIAL_IDEA ─────────────────────
    # we route all non-pipeline pre-analysis turns through chat_interaction so
    # the LLM generates the reply (with a pre-analysis system prompt); intent
    # classification still decides WHETHER to run the pipeline — only the reply
    # text generation is delegated to Gemini; heuristic `_casual_response` /
    # `_smart_followup` survive only as fallbacks inside _chat_fallback when
    # the LLM is unavailable or fails

    is_greeting = wc <= 6 and any(t == g or t.startswith(g) for g in _GREET_TOKENS)
    is_meta     = any(phrase in t for phrase in _META_PHRASES)
    is_purely_vague = (
        wc <= 15
        and any(t.startswith(v) or t == v.strip() for v in _VAGUE_STARTERS)
        and not _extract_components(last_user_msg)["has_problem"]
        and not _extract_components(last_user_msg)["has_solution"]
    )

    if intent in ('CASUAL', 'PARTIAL_IDEA') or is_greeting or is_meta or is_purely_vague:
        _TRACE_LOG.info("[TRACE][interact] BRANCH: PRE-ANALYSIS-CHAT | intent=%s | is_greeting=%s | is_meta=%s | is_purely_vague=%s",
                        intent, is_greeting, is_meta, is_purely_vague)
        chat_req = ChatRequest(context=resolved_ctx, messages=req.messages,
                               session_id=req.session_id)
        chat_res = await chat_interaction(chat_req)
        reply    = chat_res.get("reply", "")
        is_fb    = chat_res.get("is_fallback", False)

        # PARTIAL_IDEA where the user is actually sharing idea content → track
        # clarification state so the gather bar updates correctly.
        # Greetings, meta questions, and vague starters → plain 'chat' response
        # (no gather bar, no "Missing: X" chips on the first exchange).
        is_idea_content = (
            intent == 'PARTIAL_IDEA'
            and not is_purely_vague
            and not is_greeting
            and not is_meta
        )
        if is_idea_content:
            prior_state  = resolved_ctx.get("clarification_state", {}) or {}
            merged_state = _extract_components(last_user_msg, prior_state)
            return _interact_payload_or_500(lambda: build_response_payload(
                outcome='pre_analysis',
                reply=reply,
                type_='clarifying',
                clarification_state=merged_state,
                is_fallback=is_fb,
            ))
        return _interact_payload_or_500(lambda: build_response_payload(
            outcome='pre_analysis', reply=reply, type_='chat', is_fallback=is_fb,
        ))

    # ── ANALYSIS_REQUEST or OVERRIDE_COMMAND: we run the pipeline ──────────────────
    _TRACE_LOG.info("[TRACE][interact] BRANCH: PIPELINE (ANALYSIS_REQUEST/OVERRIDE) | LLM not called for routing")
    analysis_text = _build_analysis_text(last_user_msg, resolved_ctx, req.messages)
    try:
        raw = process_idea(analysis_text)
    except Exception as pipeline_err:
        log_failure(request_id, endpoint="/interact", kind="pipeline_error",
                    detail=f"{type(pipeline_err).__name__}: {pipeline_err!r}")
        raise HTTPException(status_code=500, detail=f"pipeline_error: {pipeline_err!r}")

    if raw.get("invalid_idea"):
        verdict  = raw.get("one_line_verdict", "Not a viable business concept.")
        missing  = raw.get("what_is_missing", "")
        reply    = verdict
        if missing:
            reply += f"\n\n**What's missing:** {missing}"
        payload = _interact_payload_or_500(lambda: build_response_payload(
            raw, outcome='rejected', reply=reply, type_='invalid',
        ))
        log_decision(request_id, raw, endpoint="/interact:rejected")
        return payload

    if raw.get("clarification_required"):
        # pipeline says insufficient data — don't show analysis output, just ask ONE question
        _TRACE_LOG.warning("[TRACE][interact] LLM SKIPPED → pipeline returned clarification_required → _smart_followup")
        merged_state = _extract_components(analysis_text, resolved_ctx.get("clarification_state"))
        reply = _smart_followup(analysis_text, req.messages, merged_state)
        _TRACE_LOG.warning("[TRACE][interact] SMART_FOLLOWUP FINAL STRING: %r", reply)
        payload = _interact_payload_or_500(lambda: build_response_payload(
            outcome='pre_analysis', reply=reply, type_='clarifying',
            clarification_state=merged_state,
        ))
        log_decision(request_id, raw, endpoint="/interact:clarification_required")
        return payload

    # Decided outcome → we run the operator reply, wrap in payload, and persist the session
    reply = _generate_operator_reply(raw, analysis_text)
    payload = _interact_payload_or_500(lambda: build_response_payload(
        raw, outcome='decided', reply=reply, type_='analysis',
    ))
    _store_session(req.session_id, raw)
    log_decision(request_id, raw, endpoint="/interact:decided")
    return payload


@api.post("/outcome")
async def submit_outcome(req: OutcomeSubmission):
    """
    Record a long-horizon outcome for a prior /analyze decision.

    The body must supply the decision_id returned by /analyze, plus the
    observed outcome_value once it is known ("validated", "invalidated",
    "partial", "pending", or "unknown"). All other fields are optional
    context that improves per-regime calibration accuracy over time.

    Returns {"status": "ok", "decision_id": ...} on success.
    4xx on schema violation, 500 on write failure.
    """
    result = log_outcome(
        decision_id=req.decision_id,
        sector=req.sector,
        country=req.country,
        regime=req.regime,
        predicted_state=req.predicted_state,
        outcome_value=req.outcome_value,
        react_path=req.react_path,
        intelligent_score=req.intelligent_score,
        is_components=req.is_components,
        time_to_outcome_days=req.time_to_outcome_days,
        outcome_notes=req.outcome_notes,
        supersedes_decision_id=req.supersedes_decision_id,
    )
    if result["status"] == "validation_error":
        raise HTTPException(status_code=422, detail=result["errors"])
    if result["status"] == "write_error":
        raise HTTPException(status_code=500, detail=result["error"])
    return result


@api.get("/drift")
async def drift_status():
    """
    Return current dual-signal drift status, prediction log size,
    and the last retrain status (if any retrain has been triggered).

    This endpoint is read-only — it does NOT trigger a retrain.
    Use it from the dashboard Zone 6 to display system health.

    Response shape:
        {
            drift:                  {drift_detected, signal_1_gap_fired, signal_2_centroid_fired,
                                     macro_staleness_alert, macro_days_stale,
                                     log_entries_analyzed, details},
            retrain_status:         null | {last_check_at, triggered, retrain_status, ...},
            prediction_log_entries: int,
            calibration_summary:    {total_outcomes, scored_outcomes, calibration_status, ...},
        }
    """
    drift_result = check_drift(drift_baseline)  # drift_baseline from midan.core wildcard import

    # Read retrain_status.json (written by maybe_trigger_retrain in drift_monitor)
    _logs_dir   = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "logs")
    _status_path = os.path.join(_logs_dir, "retrain_status.json")
    retrain_status = None
    if os.path.exists(_status_path):
        try:
            with open(_status_path, 'r', encoding='utf-8') as _f:
                retrain_status = json.load(_f)
        except Exception:
            pass

    all_entries   = load_prediction_log(limit=0)
    calibration   = compute_calibration_metrics()

    return {
        "drift":                  drift_result,
        "retrain_status":         retrain_status,
        "prediction_log_entries": len(all_entries),
        "calibration_summary":    {
            k: calibration[k]
            for k in ("total_outcomes", "scored_outcomes", "calibration_status", "overall_accuracy", "note")
        },
    }


@api.get("/health")
async def health():
    return {
        "status":        "ok",
        "models_loaded": MODELS_LOADED,
        "version":       "3.0 — conversation intelligence + 3-tier L0 + how_to_fix engine",
    }


@api.get("/rejection-patterns")
async def rejection_patterns():
    """Returns session-level rejection pattern statistics for analysis."""
    if not _REJECTION_LOG:
        return {"total": 0, "patterns": [], "by_severity": {}, "by_type": {}}
    from collections import Counter
    by_type     = Counter(r['type']     for r in _REJECTION_LOG)
    by_severity = Counter(r['severity'] for r in _REJECTION_LOG)
    recent = _REJECTION_LOG[-10:][::-1]
    return {
        "total":       len(_REJECTION_LOG),
        "by_severity": dict(by_severity),
        "by_type":     dict(by_type),
        "recent":      [{"type": r['type'], "severity": r['severity'], "snippet": r['snippet']} for r in recent],
    }


_HTML_FILE = pathlib.Path(__file__).parent.parent / "midan.html"


@api.get("/")
@api.get("/midan.html")
async def serve_frontend():
    return FileResponse(str(_HTML_FILE), media_type="text/html")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("api:api", host="0.0.0.0", port=8002, reload=True)



# we export everything defined in this module — including underscore-prefixed helpers —
# so other midan submodules can wildcard-import the full surface
__all__ = [name for name in list(globals().keys()) if not name.startswith('__')]
